### ISSUE TITLE
Default Folder X Script for LaunchBar

### ISSUE THREAD

**Issue by egorenar** [mlinzner/LaunchBarActions#3]
Hi,

i have a problem with your script on macOS Sierra with Default Folder X 5.0.6.

I get the following message when i try to use you script with LaunchBar:

An error occurred while running “Default Folder X Files”

Error: File not readable at path: /Users/egorenar/Library/Application Support/LaunchBar/Actions/Default Folder X Files.lbaction/Contents/Scripts/./GetDFXData.scpt (line 7).

I'm using a case-sensitive filesystem in case it matters.

Regards

**Comment by egorenar** [comment]
Hi again,

i could fix the problem.
It is indeed a problem with the filesystem.
I renamed file 'getDFXData.scpt' to 'GetDFXData.scpt' and it works.

regards

**Comment by mlinzner** [comment]
Thanks, should be fixed!
